language: c

matrix:
    allow_failures:
        - os: osx
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
        - os: osx
          osx_image: xcode7.3
          compiler: gcc
        - os: osx
          osx_image: xcode7.3
          compiler: clang
        - os: osx
          osx_image: xcode7.1
          compiler: gcc
        - os: osx
          osx_image: xcode7.1
          compiler: clang

addons:
    apt:
        packages:
            - python

before_script:
    - wget https://github.com/vslavik/bakefile/releases/download/v1.2.5.1/bakefile-1.2.5.1_beta-bin.tar.bz2 -O /tmp/bakefile.tar.bz2
    - tar xjvf /tmp/bakefile.tar.bz2
    - export PATH=$PATH:$PWD/bakefile-1.2.5.1_beta
script:
    - bkl wudecrypt.bkl
    - make

notifications:
    email:
        recipients:
            - michael@armbrust.me
        on_success: change
        on_failure: always
